"""Create clear ROI postprocessing plots from ``roi_summary.csv``.

The plotting code is intentionally direct and thesis-script friendly:

1. Read ROI summary rows generated by ``roi_postprocessing.py``.
2. Read the global force/displacement CSV so each frame title can report where
   it sits in the loading cycle.
3. Save full technical plots and simplified representative-ROI plots.
"""

from __future__ import annotations

import argparse
import math
import re
from dataclasses import dataclass
from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
from matplotlib.patches import Wedge
import numpy as np
import pandas as pd


ROI_RE = re.compile(r"roi_(left|right)_(\d+)$")
PHASE_COLUMNS = ["Phase 0", "Phase 1", "Phase 2", "Phase 3"]
PHASE_COLORS = ["#4C78A8", "#F58518", "#54A24B", "#B279A2"]
COMBINED_EQUAL_YIELD_PHASE_GROUPS = [
    ("Phase 0", ["Phase 0"], "#4C78A8"),
    ("Phase 1", ["Phase 1"], "#F58518"),
    ("Phases 2+3", ["Phase 2", "Phase 3"], "#54A24B"),
]
SEPARATE_PHASE_GROUPS = [(phase, [phase], color) for phase, color in zip(PHASE_COLUMNS, PHASE_COLORS)]
STRESS_COLOR = "#6A3D9A"
PLASTIC_COLOR = "#4D4D4D"
LOW_STRESS_COLOR = "#1F77B4"
HIGH_STRESS_COLOR = "#D62728"
YOUNGS_MODULUS_MPA = 71000.0
SIF_SHAPE_FACTOR = 1.12

# Presentation update for the strainRratio-1 ROI slides: all explicit font
# sizes are +4 points from the previous plots, and the canvases keep the same
# width while gaining vertical room for slide layouts with more height.
ROI_FONT_SIZE_INCREASE_POINTS = 4
ROI_BASE_FONTSIZE = 14
ROI_AXES_TITLE_FONTSIZE = 16
ROI_TITLE_FONTSIZE = 18
ROI_LOCATION_TITLE_FONTSIZE = 16
ROI_EDGE_LABEL_FONTSIZE = 13
ROI_SMALL_LEGEND_FONTSIZE = 12
ROI_SMALL_ANNOTATION_FONTSIZE = 12
FULL_RESPONSE_GROUPED_FIGSIZE = (14, 13.8)
FULL_RESPONSE_PAIRED_FIGSIZE = (None, 13.5)
FULL_RESPONSE_PAIRED_FIGSIZE_BASE_HEIGHT = FULL_RESPONSE_PAIRED_FIGSIZE[1]
SIF_GROUPED_FIGSIZE = (14, 10.8)
SIF_PAIRED_FIGSIZE = (None, 10.9)
SIF_PAIRED_FIGSIZE_BASE_HEIGHT = SIF_PAIRED_FIGSIZE[1]
REPRESENTATIVE_FIGSIZE = (11, 7.8)
LOCATION_MAP_FIGSIZE = (5.2, 9.0)

plt.rcParams.update(
    {
        "font.size": ROI_BASE_FONTSIZE,
        "axes.labelsize": ROI_BASE_FONTSIZE,
        "axes.titlesize": ROI_AXES_TITLE_FONTSIZE,
        "xtick.labelsize": ROI_BASE_FONTSIZE,
        "ytick.labelsize": ROI_BASE_FONTSIZE,
        "legend.fontsize": ROI_BASE_FONTSIZE,
    }
)


@dataclass(frozen=True)
class FrameContext:
    frame_number: int | None
    step_time: float
    global_strain: float
    global_stress: float
    global_plastic_strain: float


@dataclass(frozen=True)
class RepresentativeSelection:
    low_stress_high_plastic_roi: str
    high_stress_low_plastic_roi: str
    metrics: pd.DataFrame


def parse_roi_name(roi_name: str) -> tuple[str, int]:
    match = ROI_RE.match(str(roi_name))
    if not match:
        raise ValueError(f"ROI name must look like roi_left_01 or roi_right_01: {roi_name}")
    side, number = match.groups()
    return side, int(number)


def format_roi_label(roi_name: str) -> str:
    """Convert ``roi_left_01`` to ``Left ROI 01`` for plot labels."""
    side, number = parse_roi_name(roi_name)
    return f"{side.capitalize()} ROI {number:02d}"


def ordered_roi_names(roi_names, mode: str = "grouped_by_side") -> list[str]:
    """Return ROI names in one of the two requested presentation orders."""
    names = sorted(set(str(name) for name in roi_names), key=lambda name: (parse_roi_name(name)[0], parse_roi_name(name)[1]))
    if mode == "grouped_by_side":
        side_rank = {"left": 0, "right": 1}
        return sorted(names, key=lambda name: (side_rank[parse_roi_name(name)[0]], parse_roi_name(name)[1]))
    if mode == "paired_by_height":
        side_rank = {"left": 0, "right": 1}
        return sorted(names, key=lambda name: (parse_roi_name(name)[1], side_rank[parse_roi_name(name)[0]]))
    raise ValueError(f"Unknown ROI ordering mode: {mode}")


def read_global_cycle_csv(cycle_csv: str | Path) -> pd.DataFrame:
    """Read the global cycle CSV written by getForceDisp.py."""
    cycle_path = Path(cycle_csv)
    return pd.read_csv(cycle_path, skiprows=2).dropna(how="all")


def frame_context_from_cycle_csv(
    cycle_csv: str | Path,
    step_time: float,
    frame_number: int | None = None,
    youngs_modulus_mpa: float = YOUNGS_MODULUS_MPA,
) -> FrameContext:
    """Find the nearest global cycle row and compute global plastic strain amplitude."""
    cycle_data = read_global_cycle_csv(cycle_csv)
    row_index = (cycle_data["Step Time"].astype(float) - float(step_time)).abs().idxmin()
    row = cycle_data.loc[row_index]
    global_strain = float(row["U_Y"])
    global_stress = float(row["Total RF Y"])
    global_plastic_strain = max(abs(global_strain) - abs(global_stress) / youngs_modulus_mpa, 0.0)
    return FrameContext(
        frame_number=frame_number,
        step_time=float(row["Step Time"]),
        global_strain=global_strain,
        global_stress=global_stress,
        global_plastic_strain=global_plastic_strain,
    )


def _format_percent_strain(global_strain: float) -> str:
    """Format strain as a compact signed percentage for figure titles."""
    strain_percent = float(global_strain) * 100.0
    percent_text = f"{strain_percent:+.2f}".rstrip("0").rstrip(".")
    return f"{percent_text}% strain"


def build_frame_title(prefix: str, frame_number: int, step_time: float, global_strain: float) -> str:
    """Build a compact title with only the global strain context requested for plots."""
    return f"{prefix} — at {_format_percent_strain(global_strain)}"


def build_frame_filename(stem: str, extension: str = ".png") -> str:
    """Build a plain figure filename; strain context belongs in the title."""
    extension = extension if extension.startswith(".") else f".{extension}"
    return f"{stem}{extension}"


def global_stress_intensity_factor(global_stress_mpa: float, characteristic_length_m: float = 0.1e-3) -> float:
    """Estimate the global SIF reference using the same length scale as ROI summaries."""
    return SIF_SHAPE_FACTOR * float(global_stress_mpa) * math.sqrt(math.pi * characteristic_length_m)


def phase_plot_groups(combine_equal_yield_phases: bool = True) -> list[tuple[str, list[str], str]]:
    """Return phase groups for stacked volume-fraction plots.

    Phases 2 and 3 currently share the same yield stress in this model, so the
    default presentation combines them.  Passing ``False`` keeps all four phases
    separate if future model definitions assign different yield behavior.
    """
    return COMBINED_EQUAL_YIELD_PHASE_GROUPS if combine_equal_yield_phases else SEPARATE_PHASE_GROUPS


def roi_half_circle_angles(side: str) -> tuple[int, int]:
    """Return wedge angles that show each edge ROI as a half-circle inside the model."""
    if side == "left":
        return -90, 90
    if side == "right":
        return 90, 270
    raise ValueError(f"Unknown ROI side: {side}")


def select_representative_rois(
    frame_data: pd.DataFrame,
    global_stress: float,
    global_plastic_strain: float,
) -> RepresentativeSelection:
    """Select contrasting ROIs using absolute stress magnitude ratios.

    Low-stress/high-plastic score favors low |local stress| / |global stress| and
    high local plastic strain / global plastic strain.  High-stress/low-plastic
    score does the opposite.
    """
    metrics = frame_data.set_index("roi_name").copy()
    stress_denominator = abs(float(global_stress))
    if math.isclose(stress_denominator, 0.0):
        stress_denominator = max(metrics["average_stress_mpa"].abs().max(), 1.0)
    plastic_denominator = float(global_plastic_strain)
    if math.isclose(plastic_denominator, 0.0):
        plastic_denominator = max(metrics["average_plastic_strain"].max(), 1.0e-12)

    metrics["stress_ratio"] = metrics["average_stress_mpa"].abs() / stress_denominator
    metrics["plastic_ratio"] = metrics["average_plastic_strain"] / plastic_denominator
    metrics["low_stress_high_plastic_score"] = metrics["plastic_ratio"] / metrics["stress_ratio"].replace(0.0, np.nan)
    metrics["high_stress_low_plastic_score"] = metrics["stress_ratio"] / metrics["plastic_ratio"].replace(0.0, np.nan)
    metrics = metrics.replace([np.inf, -np.inf], np.nan).fillna(0.0)

    low_candidates = metrics[metrics["stress_ratio"] < 1.0]
    if low_candidates.empty:
        # If all ROIs are above the global stress magnitude, still choose the
        # best explanatory contrast by balancing high plasticity against stress.
        low_high = str(metrics["low_stress_high_plastic_score"].idxmax())
    else:
        low_high = str(low_candidates["plastic_ratio"].idxmax())

    high_candidates = metrics[metrics["stress_ratio"] > 1.0]
    if low_high in high_candidates.index:
        high_candidates = high_candidates.drop(index=low_high)
    if high_candidates.empty:
        high_candidates = metrics.drop(index=low_high)
        high_low = str(high_candidates["high_stress_low_plastic_score"].idxmax())
    else:
        high_low = str(high_candidates["plastic_ratio"].idxmin())
    return RepresentativeSelection(low_high, high_low, metrics)


def _save_figure(fig, output_path: Path) -> None:
    output_path.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(output_path, dpi=300, bbox_inches="tight")
    fig.savefig(output_path.with_suffix(".svg"), bbox_inches="tight")
    plt.close(fig)


def _apply_group_shading(ax, order: list[str], mode: str, enabled: bool, show_edge_labels: bool = True) -> None:
    if not enabled:
        return
    if mode == "grouped_by_side":
        left_count = sum(1 for name in order if parse_roi_name(name)[0] == "left")
        ax.axvspan(-0.5, left_count - 0.5, color="#EAF2F8", alpha=0.75, zorder=0)
        ax.axvspan(left_count - 0.5, len(order) - 0.5, color="#FDEDEC", alpha=0.60, zorder=0)
        if 0 < left_count < len(order):
            ax.axvline(left_count - 0.5, color="#666666", linestyle="--", linewidth=1.0, alpha=0.85, zorder=1)
        if show_edge_labels:
            ax.text((left_count - 1) / 2, 0.98, "Left edge", transform=ax.get_xaxis_transform(), ha="center", va="top", fontsize=ROI_EDGE_LABEL_FONTSIZE)
            ax.text((left_count + len(order) - 1) / 2, 0.98, "Right edge", transform=ax.get_xaxis_transform(), ha="center", va="top", fontsize=ROI_EDGE_LABEL_FONTSIZE)
    elif mode == "paired_by_height":
        for pair_start in range(0, len(order), 2):
            if (pair_start // 2) % 2 == 0:
                ax.axvspan(pair_start - 0.5, pair_start + 1.5, color="#F4F6F7", alpha=0.75, zorder=0)
            pair_end = pair_start + 1.5
            if pair_end < len(order) - 0.5:
                ax.axvline(pair_end, color="#666666", linestyle="--", linewidth=1.0, alpha=0.85, zorder=1)


def _plot_pair_segments(ax, x, values, pair_size: int = 2, **plot_kwargs) -> None:
    """Plot separate point groups so paired ROI groups are not connected."""
    x_values = np.asarray(x)
    y_values = np.asarray(values, dtype=float)
    base_label = plot_kwargs.pop("label", None)
    for start in range(0, len(x_values), pair_size):
        stop = min(start + pair_size, len(x_values))
        segment_kwargs = dict(plot_kwargs)
        if base_label is not None:
            segment_kwargs["label"] = base_label if start == 0 else "_nolegend_"
        ax.plot(x_values[start:stop], y_values[start:stop], **segment_kwargs)


def plot_full_response(
    frame_data: pd.DataFrame,
    context: FrameContext,
    output_path: str | Path,
    mode: str,
    shaded_bands: bool = True,
    combine_equal_yield_phases: bool = True,
) -> Path:
    """Create the multi-panel full technical ROI response plot."""
    order = ordered_roi_names(frame_data["roi_name"], mode=mode)
    data = frame_data.set_index("roi_name").loc[order]
    x = np.arange(len(order))
    labels = [format_roi_label(name) for name in order]

    if mode == "grouped_by_side":
        fig, axes = plt.subplots(
            3,
            2,
            figsize=FULL_RESPONSE_GROUPED_FIGSIZE,
            sharey="row",
            gridspec_kw={"height_ratios": [1.0, 1.0, 1.25]},
        )
        fig.suptitle(
            build_frame_title("ROI response and phase fractions split by side", int(context.frame_number), context.step_time, context.global_strain),
            fontsize=ROI_TITLE_FONTSIZE,
            y=0.995,
        )
        side_specs = [("left", "Left ROI"), ("right", "Right ROI")]
        for column_index, (side, side_title) in enumerate(side_specs):
            side_order = [name for name in order if parse_roi_name(name)[0] == side]
            side_data = data.loc[side_order]
            side_x = np.arange(len(side_order))
            side_labels = [format_roi_label(name) for name in side_order]

            stress_ax = axes[0, column_index]
            stress_ax.plot(side_x, side_data["average_stress_mpa"], marker="o", color=STRESS_COLOR, linewidth=2.0, label="ROI average S22")
            stress_ax.axhline(context.global_stress, color=STRESS_COLOR, linestyle="--", linewidth=1.4, label="Global stress")
            stress_ax.set_title(f"{side_title} stress")
            stress_ax.grid(True, axis="y", alpha=0.3)
            stress_ax.set_xticks(side_x)
            stress_ax.set_xticklabels([])
            stress_ax.set_xlim(-0.5, len(side_order) - 0.5)

            plastic_ax = axes[1, column_index]
            plastic_values = side_data["average_plastic_strain"].clip(lower=1.0e-12)
            plastic_ax.plot(side_x, plastic_values, marker="s", color=PLASTIC_COLOR, linewidth=2.0, label="ROI average plastic strain")
            if context.global_plastic_strain > 0.0:
                plastic_ax.axhline(context.global_plastic_strain, color=PLASTIC_COLOR, linestyle="--", linewidth=1.4, label="Global plastic strain estimate")
            plastic_ax.set_yscale("log")
            plastic_ax.set_title(f"{side_title} plastic strain")
            plastic_ax.grid(True, axis="y", alpha=0.3, which="both")
            plastic_ax.set_xticks(side_x)
            plastic_ax.set_xticklabels([])
            plastic_ax.set_xlim(-0.5, len(side_order) - 0.5)

            volume_ax = axes[2, column_index]
            bottom = np.zeros(len(side_order))
            for label, columns, color in phase_plot_groups(combine_equal_yield_phases=combine_equal_yield_phases):
                values = side_data[columns].sum(axis=1).to_numpy(dtype=float)
                volume_ax.bar(side_x, values, bottom=bottom, color=color, label=label, width=0.72)
                bottom += values
            volume_ax.set_title(f"{side_title} volume fractions")
            volume_ax.set_ylim(0, 100)
            volume_ax.grid(True, axis="y", alpha=0.25)
            volume_ax.set_xticks(side_x)
            volume_ax.set_xticklabels(side_labels, rotation=45, ha="right")
            volume_ax.set_xlim(-0.5, len(side_order) - 0.5)

        axes[0, 0].set_ylabel("Stress S22 (MPa)")
        axes[1, 0].set_ylabel("Plastic strain\n(log scale)")
        axes[2, 0].set_ylabel("Phase fraction (%)")
        axes[0, 1].legend(loc="best")
        axes[1, 1].legend(loc="best")
        axes[2, 1].legend(ncol=3, loc="upper center", bbox_to_anchor=(0.5, -0.42))
        fig.tight_layout(rect=[0, 0.04, 1, 0.955])

        output = Path(output_path)
        _save_figure(fig, output)
        return output

    fig, axes = plt.subplots(3, 1, figsize=(max(12, 0.62 * len(order)), FULL_RESPONSE_PAIRED_FIGSIZE_BASE_HEIGHT), sharex=True, gridspec_kw={"height_ratios": [1.0, 1.0, 1.25]})
    title_mode = "Paired by vertical position"
    fig.suptitle(build_frame_title(f"ROI response and phase fractions ({title_mode})", int(context.frame_number), context.step_time, context.global_strain), fontsize=ROI_TITLE_FONTSIZE, y=0.995)

    # Stress panel
    _plot_pair_segments(axes[0], x, data["average_stress_mpa"], marker="o", linestyle="None", color=STRESS_COLOR, label="ROI average S22")
    axes[0].axhline(context.global_stress, color=STRESS_COLOR, linestyle="--", linewidth=1.4, label="Global stress")
    axes[0].set_ylabel("Stress S22 (MPa)")
    axes[0].grid(True, axis="y", alpha=0.3)
    axes[0].legend(loc="best")

    # Plastic strain panel
    plastic_values = data["average_plastic_strain"].clip(lower=1.0e-12)
    _plot_pair_segments(axes[1], x, plastic_values, marker="s", linestyle="None", color=PLASTIC_COLOR, label="ROI average plastic strain")
    if context.global_plastic_strain > 0.0:
        axes[1].axhline(context.global_plastic_strain, color=PLASTIC_COLOR, linestyle="--", linewidth=1.4, label="Global plastic strain estimate")
    axes[1].set_yscale("log")
    axes[1].set_ylabel("Plastic strain\n(log scale)")
    axes[1].grid(True, axis="y", alpha=0.3, which="both")
    axes[1].legend(loc="best")

    # Phase fractions panel
    bottom = np.zeros(len(order))
    for label, columns, color in phase_plot_groups(combine_equal_yield_phases=combine_equal_yield_phases):
        values = data[columns].sum(axis=1).to_numpy(dtype=float)
        axes[2].bar(x, values, bottom=bottom, color=color, label=label, width=0.72)
        bottom += values
    axes[2].set_ylabel("Phase fraction (%)")
    axes[2].set_ylim(0, 100)
    axes[2].grid(True, axis="y", alpha=0.25)
    axes[2].legend(ncol=3, loc="upper center", bbox_to_anchor=(0.5, -0.42))

    for axis_index, ax in enumerate(axes):
        _apply_group_shading(ax, order, mode, shaded_bands, show_edge_labels=(axis_index != 2))
        ax.set_xlim(-0.5, len(order) - 0.5)

    axes[2].set_xticks(x)
    axes[2].set_xticklabels(labels, rotation=45, ha="right")
    fig.tight_layout(rect=[0, 0.04, 1, 0.965])

    output = Path(output_path)
    _save_figure(fig, output)
    return output


def plot_sif_volume_fraction_comparison(
    frame_data: pd.DataFrame,
    context: FrameContext,
    output_path: str | Path,
    mode: str,
    shaded_bands: bool = True,
    combine_equal_yield_phases: bool = True,
) -> Path:
    """Create a two-panel SIF and local volume-fraction plot for all ROIs."""
    order = ordered_roi_names(frame_data["roi_name"], mode=mode)
    data = frame_data.set_index("roi_name").loc[order]
    x = np.arange(len(order))
    labels = [format_roi_label(name) for name in order]

    if mode == "grouped_by_side":
        fig, axes = plt.subplots(2, 2, figsize=SIF_GROUPED_FIGSIZE, sharey="row")
        fig.suptitle(
            build_frame_title("ROI stress intensity and volume fractions split by side", int(context.frame_number), context.step_time, context.global_strain),
            fontsize=ROI_TITLE_FONTSIZE,
            y=0.995,
        )
        side_specs = [("left", "Left ROI"), ("right", "Right ROI")]
        for column_index, (side, side_title) in enumerate(side_specs):
            side_order = [name for name in order if parse_roi_name(name)[0] == side]
            side_data = data.loc[side_order]
            side_x = np.arange(len(side_order))
            side_labels = [format_roi_label(name) for name in side_order]

            sif_ax = axes[0, column_index]
            sif_ax.plot(side_x, side_data["stress_intensity_factor"], marker="o", color=STRESS_COLOR, linewidth=2.0, label="ROI SIF")
            sif_ax.axhline(global_stress_intensity_factor(context.global_stress), color=STRESS_COLOR, linestyle="--", linewidth=1.4, label="Global SIF")
            sif_ax.set_title(f"{side_title} SIF")
            sif_ax.grid(True, axis="y", alpha=0.3)
            sif_ax.set_xticks(side_x)
            sif_ax.set_xticklabels([])
            sif_ax.set_xlim(-0.5, len(side_order) - 0.5)

            volume_ax = axes[1, column_index]
            bottom = np.zeros(len(side_order))
            for label, columns, color in phase_plot_groups(combine_equal_yield_phases=combine_equal_yield_phases):
                values = side_data[columns].sum(axis=1).to_numpy(dtype=float)
                volume_ax.bar(side_x, values, bottom=bottom, color=color, label=label, width=0.72)
                bottom += values
            volume_ax.set_title(f"{side_title} volume fractions")
            volume_ax.set_ylim(0, 100)
            volume_ax.grid(True, axis="y", alpha=0.25)
            volume_ax.set_xticks(side_x)
            volume_ax.set_xticklabels(side_labels, rotation=45, ha="right")
            volume_ax.set_xlim(-0.5, len(side_order) - 0.5)

        axes[0, 0].set_ylabel("Stress intensity factor")
        axes[1, 0].set_ylabel("Volume fraction (%)")
        axes[0, 1].legend(loc="best")
        axes[1, 1].legend(ncol=3, loc="upper center", bbox_to_anchor=(0.5, -0.42))
        fig.tight_layout(rect=[0, 0.04, 1, 0.955])

        output = Path(output_path)
        _save_figure(fig, output)
        return output

    fig, axes = plt.subplots(2, 1, figsize=(max(12, 0.62 * len(order)), SIF_PAIRED_FIGSIZE_BASE_HEIGHT), sharex=True, gridspec_kw={"height_ratios": [1.0, 1.25]})
    title_mode = "Paired by vertical position"
    fig.suptitle(build_frame_title(f"ROI stress intensity and volume fractions ({title_mode})", int(context.frame_number), context.step_time, context.global_strain), fontsize=ROI_TITLE_FONTSIZE, y=0.995)

    _plot_pair_segments(axes[0], x, data["stress_intensity_factor"], marker="o", color=STRESS_COLOR, linewidth=2.0, label="ROI SIF")
    axes[0].axhline(global_stress_intensity_factor(context.global_stress), color=STRESS_COLOR, linestyle="--", linewidth=1.4, label="Global SIF")
    axes[0].set_ylabel("Stress intensity factor")
    axes[0].grid(True, axis="y", alpha=0.3)
    axes[0].legend(loc="best")

    bottom = np.zeros(len(order))
    for label, columns, color in phase_plot_groups(combine_equal_yield_phases=combine_equal_yield_phases):
        values = data[columns].sum(axis=1).to_numpy(dtype=float)
        axes[1].bar(x, values, bottom=bottom, color=color, label=label, width=0.72)
        bottom += values
    axes[1].set_ylabel("Volume fraction (%)")
    axes[1].set_ylim(0, 100)
    axes[1].grid(True, axis="y", alpha=0.25)
    axes[1].legend(ncol=3, loc="upper center", bbox_to_anchor=(0.5, -0.42))

    for axis_index, ax in enumerate(axes):
        _apply_group_shading(ax, order, mode, shaded_bands, show_edge_labels=(axis_index == 0))
        ax.set_xlim(-0.5, len(order) - 0.5)

    axes[1].set_xticks(x)
    axes[1].set_xticklabels(labels, rotation=45, ha="right")
    fig.tight_layout(rect=[0, 0.06, 1, 0.955])

    output = Path(output_path)
    _save_figure(fig, output)
    return output


def plot_representative_comparison(
    frame_data: pd.DataFrame,
    context: FrameContext,
    output_path: str | Path,
    combine_equal_yield_phases: bool = True,
) -> Path:
    """Create the two-ROI explanatory plot with normalized response and phases."""
    selection = select_representative_rois(frame_data, context.global_stress, context.global_plastic_strain)
    selected_names = [selection.low_stress_high_plastic_roi, selection.high_stress_low_plastic_roi]
    labels = [format_roi_label(name) for name in selected_names]
    metrics = selection.metrics.loc[selected_names]
    phase_data = frame_data.set_index("roi_name").loc[selected_names, PHASE_COLUMNS]

    fig, axes = plt.subplots(1, 2, figsize=REPRESENTATIVE_FIGSIZE, gridspec_kw={"width_ratios": [1.05, 1.0]})
    fig.suptitle(build_frame_title("Two representative ROI responses", int(context.frame_number), context.step_time, context.global_strain), fontsize=ROI_TITLE_FONTSIZE)

    # Normalized response bars
    x = np.arange(len(selected_names))
    width = 0.34
    axes[0].bar(x - width / 2, metrics["stress_ratio"], width=width, color=STRESS_COLOR, label="Normalized stress")
    axes[0].bar(x + width / 2, metrics["plastic_ratio"], width=width, color=PLASTIC_COLOR, label="Normalized strain")
    axes[0].axhline(1.0, color="black", linestyle="--", linewidth=1.0, alpha=0.8)
    axes[0].set_xticks(x)
    axes[0].set_xticklabels(labels, rotation=20, ha="right")
    axes[0].set_ylabel("Normalized value")
    axes[0].set_title("mechanical response relative to global response")
    axes[0].grid(True, axis="y", alpha=0.3)
    axes[0].legend(fontsize=ROI_SMALL_LEGEND_FONTSIZE, loc="upper center", bbox_to_anchor=(0.5, -0.16))
    annotation_y = axes[0].get_ylim()[1] * 0.90
    text_box = {"boxstyle": "round,pad=0.25", "facecolor": "white", "edgecolor": "none", "alpha": 0.75}
    axes[0].text(x[0], annotation_y, "Lower stress\nhigher plastic", ha="center", va="top", color=LOW_STRESS_COLOR, fontsize=ROI_SMALL_ANNOTATION_FONTSIZE, bbox=text_box)
    axes[0].text(x[1], annotation_y, "Higher stress\nlower plastic", ha="center", va="top", color=HIGH_STRESS_COLOR, fontsize=ROI_SMALL_ANNOTATION_FONTSIZE, bbox=text_box)

    # Phase fractions for selected ROIs
    bottom = np.zeros(len(selected_names))
    for label, columns, color in phase_plot_groups(combine_equal_yield_phases=combine_equal_yield_phases):
        values = phase_data[columns].sum(axis=1).to_numpy(dtype=float)
        axes[1].bar(x, values, bottom=bottom, color=color, label=label, width=0.55)
        bottom += values
    axes[1].set_xticks(x)
    axes[1].set_xticklabels(labels, rotation=20, ha="right")
    axes[1].set_ylabel("Phase fraction (%)")
    axes[1].set_ylim(0, 100)
    axes[1].set_title("Local volume fractions")
    axes[1].grid(True, axis="y", alpha=0.25)
    axes[1].legend(fontsize=ROI_SMALL_LEGEND_FONTSIZE, loc="upper center", bbox_to_anchor=(0.5, -0.14), ncol=2)

    fig.tight_layout(rect=[0, 0.06, 1, 0.93])
    output = Path(output_path)
    _save_figure(fig, output)
    return output


def plot_roi_location_map(
    frame_data: pd.DataFrame,
    context: FrameContext,
    output_path: str | Path,
) -> Path:
    """Create a simple domain schematic showing selected representative ROIs."""
    selection = select_representative_rois(frame_data, context.global_stress, context.global_plastic_strain)
    selected = {
        selection.low_stress_high_plastic_roi: (LOW_STRESS_COLOR, "Lower stress / higher plastic"),
        selection.high_stress_low_plastic_roi: (HIGH_STRESS_COLOR, "Higher stress / lower plastic"),
    }

    fig, ax = plt.subplots(figsize=LOCATION_MAP_FIGSIZE)
    ax.set_title(
        build_frame_title("Selected ROI locations", int(context.frame_number), context.step_time, context.global_strain),
        fontsize=ROI_LOCATION_TITLE_FONTSIZE,
        pad=8,
    )
    ax.add_patch(plt.Rectangle((0, 0), 1, 1, fill=False, linewidth=2.0, color="black"))
    top_arrow_direction = 1.0 if context.global_strain >= 0.0 else -1.0
    arrow_start_y = 1.025 if top_arrow_direction > 0 else 1.12
    ax.arrow(
        0.5,
        arrow_start_y,
        0,
        0.08 * top_arrow_direction,
        width=0.01,
        head_width=0.05,
        head_length=0.035,
        color="black",
        clip_on=False,
        length_includes_head=True,
    )
    ax.text(0.58, 1.075, "Applied top displacement", fontsize=ROI_EDGE_LABEL_FONTSIZE, va="center")
    ax.plot([0.0, 1.0], [-0.035, -0.035], color="black", linewidth=1.6, clip_on=False)
    for support_x in np.linspace(0.08, 0.92, 8):
        ax.plot([support_x - 0.04, support_x], [-0.075, -0.035], color="black", linewidth=1.0, clip_on=False)
    ax.text(0.5, -0.12, "Bottom constrained", ha="center", va="top", fontsize=ROI_EDGE_LABEL_FONTSIZE)

    radius = 0.035
    for side in ("left", "right"):
        x = 0.0 if side == "left" else 1.0
        ha = "right" if side == "left" else "left"
        text_dx = -0.04 if side == "left" else 0.04
        for number in range(1, 10):
            roi_name = f"roi_{side}_{number:02d}"
            y = 1.0 - 0.1 - (number - 1) * 0.1
            color, description = selected.get(roi_name, ("#BDBDBD", ""))
            size = radius * (1.6 if roi_name in selected else 1.0)
            theta1, theta2 = roi_half_circle_angles(side)
            ax.add_patch(Wedge((x, y), size, theta1, theta2, facecolor=color, alpha=0.88, edgecolor="black", lw=0.6))
            if roi_name in selected:
                ax.text(x + text_dx, y, f"{format_roi_label(roi_name)}\n{description}", ha=ha, va="center", fontsize=ROI_SMALL_ANNOTATION_FONTSIZE, color=color)

    ax.set_xlim(-0.35, 1.35)
    ax.set_ylim(-0.14, 1.15)
    ax.set_aspect("equal")
    ax.axis("off")
    output = Path(output_path)
    _save_figure(fig, output)
    return output


def make_all_roi_plots(
    roi_summary_csv: str | Path,
    cycle_csv: str | Path,
    output_root: str | Path,
    combine_equal_yield_phases: bool = True,
) -> list[Path]:
    """Generate all requested ROI plot families for every frame in the summary."""
    summary = pd.read_csv(roi_summary_csv)
    output_root = Path(output_root)
    created: list[Path] = []

    for frame_number in sorted(summary["frame_number"].unique()):
        frame_data = summary[summary["frame_number"] == frame_number].copy()
        step_time = float(frame_data["step_time"].iloc[0])
        context = frame_context_from_cycle_csv(cycle_csv, step_time=step_time, frame_number=int(frame_number))
        frame_prefix = f"frame{int(frame_number)}"

        created.append(plot_full_response(
            frame_data,
            context,
            output_root / "full_response" / build_frame_filename(f"{frame_prefix}_grouped_by_side"),
            mode="grouped_by_side",
            shaded_bands=True,
            combine_equal_yield_phases=combine_equal_yield_phases,
        ))
        created.append(plot_full_response(
            frame_data,
            context,
            output_root / "full_response" / build_frame_filename(f"{frame_prefix}_paired_by_height"),
            mode="paired_by_height",
            shaded_bands=True,
            combine_equal_yield_phases=combine_equal_yield_phases,
        ))
        created.append(plot_sif_volume_fraction_comparison(
            frame_data,
            context,
            output_root / "sif_volume_fractions" / build_frame_filename(f"{frame_prefix}_sif_grouped_by_side"),
            mode="grouped_by_side",
            shaded_bands=True,
            combine_equal_yield_phases=combine_equal_yield_phases,
        ))
        created.append(plot_sif_volume_fraction_comparison(
            frame_data,
            context,
            output_root / "sif_volume_fractions" / build_frame_filename(f"{frame_prefix}_sif_paired_by_height"),
            mode="paired_by_height",
            shaded_bands=True,
            combine_equal_yield_phases=combine_equal_yield_phases,
        ))
        created.append(plot_representative_comparison(
            frame_data,
            context,
            output_root / "representative_rois" / build_frame_filename(f"{frame_prefix}_representative_roi_comparison"),
            combine_equal_yield_phases=combine_equal_yield_phases,
        ))
        created.append(plot_roi_location_map(
            frame_data,
            context,
            output_root / "location_maps" / build_frame_filename(f"{frame_prefix}_representative_roi_locations"),
        ))

    return created


def main() -> None:
    parser = argparse.ArgumentParser(description="Create ROI response/phase fraction plots.")
    parser.add_argument("--roi-summary", required=True, help="Path to roi_summary.csv")
    parser.add_argument("--cycle-csv", required=True, help="Path to global cycle CSV, e.g. strainRratio-1.csv")
    parser.add_argument("--output-root", required=True, help="Folder where plot families will be saved")
    parser.add_argument(
        "--separate-phases",
        action="store_true",
        help="Plot phases 2 and 3 separately instead of combining them as equal-yield phases.",
    )
    args = parser.parse_args()

    created = make_all_roi_plots(
        args.roi_summary,
        args.cycle_csv,
        args.output_root,
        combine_equal_yield_phases=not args.separate_phases,
    )
    print("Created ROI plots:")
    for path in created:
        print(path)
        print(path.with_suffix(".svg"))


if __name__ == "__main__":
    main()
